import { Perk } from './types';

export const mockPerks: Perk[] = [
  {
    id: '1',
    company: 'AWS',
    title: 'Activate Founders',
    description: '$1,000 in AWS Activate Credits for 2 years, valid for AWS services.',
    type: 'Cloud Credits',
    value: '$1,000',
    eligibility: 'New startup, no funding required',
    expires: '2026-12-31',
    link: 'https://aws.amazon.com/activate/',
    logo: 'AWS',
    tags: ['cloud', 'infrastructure', 'serverless'],
  },
  {
    id: '2',
    company: 'Google Cloud',
    title: 'Google for Startups',
    description: 'Up to $2,000 in Google Cloud credits for new accounts to experiment and build.',
    type: 'Cloud Credits',
    value: '$2,000',
    eligibility: 'New billing account',
    expires: '2026-06-30',
    link: 'https://cloud.google.com/startup',
    logo: 'GCP',
    tags: ['cloud', 'ai', 'firebase'],
  },
  {
    id: '3',
    company: 'GitHub',
    title: 'Student Developer Pack',
    description: 'Free access to the best developer tools in one place so you can learn by doing.',
    type: 'Tools',
    value: '$200k+',
    eligibility: 'Student status',
    expires: 'Ongoing',
    link: 'https://education.github.com/pack',
    logo: 'GIT',
    tags: ['education', 'tools', 'domains'],
  },
  {
    id: '4',
    company: 'Stripe',
    title: 'Fee-Free Processing',
    description: 'First $50,000 in processing fees waived for new startups integrated via partners.',
    type: 'API',
    value: '$1,500',
    eligibility: 'Partner referral',
    expires: '2025-12-31',
    link: 'https://stripe.com',
    logo: 'PAY',
    tags: ['payments', 'finance', 'saas'],
  },
  {
    id: '5',
    company: 'Vercel',
    title: 'Hobby Tier',
    description: 'Generous free tier for personal projects with free SSL, domains, and global CDN.',
    type: 'Cloud Credits',
    value: 'Free',
    eligibility: 'Everyone',
    expires: 'Forever',
    link: 'https://vercel.com/pricing',
    logo: '▲',
    tags: ['hosting', 'frontend', 'serverless'],
  },
];
